/**
 * Default style definitions
 * Based on rich/default_styles.py
 */
import { Style } from './style.js';

export const DEFAULT_STYLES: Record<string, Style> = {
  none: Style.null(),
  reset: new Style({
    color: 'default',
    bgcolor: 'default',
    dim: false,
    bold: false,
    italic: false,
    underline: false,
    blink: false,
    blink2: false,
    reverse: false,
    conceal: false,
    strike: false,
  }),
  dim: new Style({ dim: true }),
  bright: new Style({ dim: false }),
  bold: new Style({ bold: true }),
  strong: new Style({ bold: true }),
  code: new Style({ reverse: true, bold: true }),
  italic: new Style({ italic: true }),
  emphasize: new Style({ italic: true }),
  underline: new Style({ underline: true }),
  blink: new Style({ blink: true }),
  blink2: new Style({ blink2: true }),
  reverse: new Style({ reverse: true }),
  strike: new Style({ strike: true }),
  black: new Style({ color: 'black' }),
  red: new Style({ color: 'red' }),
  green: new Style({ color: 'green' }),
  yellow: new Style({ color: 'yellow' }),
  magenta: new Style({ color: 'magenta' }),
  cyan: new Style({ color: 'cyan' }),
  white: new Style({ color: 'white' }),
  'inspect.attr': new Style({ color: 'yellow', italic: true }),
  'inspect.attr.dunder': new Style({ color: 'yellow', italic: true, dim: true }),
  'inspect.callable': new Style({ bold: true, color: 'red' }),
  'inspect.async_def': new Style({ italic: true, color: 'bright_cyan' }),
  'inspect.def': new Style({ italic: true, color: 'bright_cyan' }),
  'inspect.class': new Style({ italic: true, color: 'bright_cyan' }),
  'inspect.error': new Style({ bold: true, color: 'red' }),
  'inspect.equals': new Style({}),
  'inspect.help': new Style({ color: 'cyan' }),
  'inspect.doc': new Style({ dim: true }),
  'inspect.value.border': new Style({ color: 'green' }),
  'live.ellipsis': new Style({ bold: true, color: 'red' }),
  'layout.tree.row': new Style({ dim: false, color: 'red' }),
  'layout.tree.column': new Style({ dim: false, color: 'blue' }),
  'logging.keyword': new Style({ bold: true, color: 'yellow' }),
  'logging.level.notset': new Style({ dim: true }),
  'logging.level.debug': new Style({ color: 'green' }),
  'logging.level.info': new Style({ color: 'blue' }),
  'logging.level.warning': new Style({ color: 'yellow' }),
  'logging.level.error': new Style({ color: 'red', bold: true }),
  'logging.level.critical': new Style({ color: 'red', bold: true, reverse: true }),
  'log.level': Style.null(),
  'log.time': new Style({ color: 'cyan', dim: true }),
  'log.message': Style.null(),
  'log.path': new Style({ dim: true }),
  'repr.ellipsis': new Style({ color: 'yellow' }),
  'repr.indent': new Style({ color: 'green', dim: true }),
  'repr.error': new Style({ color: 'red', bold: true }),
  'repr.str': new Style({ color: 'green', italic: false, bold: false }),
  'repr.brace': new Style({ bold: true }),
  'repr.comma': new Style({ bold: true }),
  'repr.ipv4': new Style({ bold: true, color: 'bright_green' }),
  'repr.ipv6': new Style({ bold: true, color: 'bright_green' }),
  'repr.eui48': new Style({ bold: true, color: 'bright_green' }),
  'repr.eui64': new Style({ bold: true, color: 'bright_green' }),
  'repr.tag_start': new Style({ bold: true }),
  'repr.tag_name': new Style({ color: 'bright_magenta', bold: true }),
  'repr.tag_contents': new Style({ color: 'default' }),
  'repr.tag_end': new Style({ bold: true }),
  'repr.attrib_name': new Style({ color: 'yellow', italic: false }),
  'repr.attrib_equal': new Style({ bold: true }),
  'repr.attrib_value': new Style({ color: 'magenta', italic: false }),
  'repr.number': new Style({ color: 'cyan', bold: true, italic: false }),
  'repr.number_complex': new Style({ color: 'cyan', bold: true, italic: false }),
  'repr.bool_true': new Style({ color: 'bright_green', italic: true }),
  'repr.bool_false': new Style({ color: 'bright_red', italic: true }),
  'repr.none': new Style({ color: 'magenta', italic: true }),
  'repr.url': new Style({ underline: true, color: 'bright_blue', italic: false, bold: false }),
  'repr.uuid': new Style({ color: 'bright_yellow', bold: false }),
  'repr.call': new Style({ color: 'magenta', bold: true }),
  'repr.path': new Style({ color: 'magenta' }),
  'repr.filename': new Style({ color: 'bright_magenta' }),
  'rule.line': new Style({ color: 'bright_green' }),
  'rule.text': Style.null(),
  'json.brace': new Style({ bold: true }),
  'json.bool_true': new Style({ color: 'bright_green', italic: true }),
  'json.bool_false': new Style({ color: 'bright_red', italic: true }),
  'json.null': new Style({ color: 'magenta', italic: true }),
  'json.number': new Style({ color: 'cyan', bold: true, italic: false }),
  'json.str': new Style({ color: 'green', italic: false, bold: false }),
  'json.key': new Style({ color: 'blue', bold: true }),
  prompt: Style.null(),
  'prompt.choices': new Style({ color: 'magenta', bold: true }),
  'prompt.default': new Style({ color: 'cyan', bold: true }),
  'prompt.invalid': new Style({ color: 'red' }),
  'prompt.invalid.choice': new Style({ color: 'red' }),
  pretty: Style.null(),
  'scope.border': new Style({ color: 'blue' }),
  'scope.key': new Style({ color: 'yellow', italic: true }),
  'scope.key.special': new Style({ color: 'yellow', italic: true, dim: true }),
  'scope.equals': new Style({ color: 'red' }),
  'table.header': new Style({ bold: true }),
  'table.footer': new Style({ bold: true }),
  'table.cell': Style.null(),
  'table.title': new Style({ italic: true }),
  'table.caption': new Style({ italic: true, dim: true }),
  'traceback.error': new Style({ color: 'red', italic: true }),
  'traceback.border.syntax_error': new Style({ color: 'bright_red' }),
  'traceback.border': new Style({ color: 'red' }),
  'traceback.text': Style.null(),
  'traceback.title': new Style({ color: 'red', bold: true }),
  'traceback.exc_type': new Style({ color: 'bright_red', bold: true }),
  'traceback.exc_value': Style.null(),
  'traceback.offset': new Style({ color: 'bright_red', bold: true }),
  'traceback.error_range': new Style({ underline: true, bold: true }),
  'traceback.note': new Style({ color: 'green', bold: true }),
  'traceback.group.border': new Style({ color: 'magenta' }),
  'bar.back': new Style({ color: 'grey23' }),
  'bar.complete': new Style({ color: 'rgb(249,38,114)' }),
  'bar.finished': new Style({ color: 'rgb(114,156,31)' }),
  'bar.pulse': new Style({ color: 'rgb(249,38,114)' }),
  'progress.description': Style.null(),
  'progress.filesize': new Style({ color: 'green' }),
  'progress.filesize.total': new Style({ color: 'green' }),
  'progress.download': new Style({ color: 'green' }),
  'progress.elapsed': new Style({ color: 'yellow' }),
  'progress.percentage': new Style({ color: 'magenta' }),
  'progress.remaining': new Style({ color: 'cyan' }),
  'progress.data.speed': new Style({ color: 'red' }),
  'progress.spinner': new Style({ color: 'green' }),
  'status.spinner': new Style({ color: 'green' }),
  tree: new Style({}),
  'tree.line': new Style({}),
  'markdown.paragraph': new Style({}),
  'markdown.text': new Style({}),
  'markdown.em': new Style({ italic: true }),
  'markdown.emph': new Style({ italic: true }),
  'markdown.strong': new Style({ bold: true }),
  'markdown.code': new Style({ bold: true, color: 'cyan', bgcolor: 'black' }),
  'markdown.code_block': new Style({ color: 'yellow', bgcolor: 'black' }),
  'markdown.block_quote': new Style({ color: 'magenta' }),
  'markdown.list': new Style({ color: 'cyan' }),
  'markdown.item': new Style({}),
  'markdown.item.bullet': new Style({ color: 'yellow', bold: true }),
  'markdown.item.number': new Style({ color: 'yellow', bold: true }),
  'markdown.hr': new Style({ color: 'yellow' }),
  'markdown.h1.border': new Style({}),
  'markdown.h1': new Style({ bold: true }),
  'markdown.h2': new Style({ bold: true, underline: true }),
  'markdown.h3': new Style({ bold: true }),
  'markdown.h4': new Style({ bold: true, dim: true }),
  'markdown.h5': new Style({ underline: true }),
  'markdown.h6': new Style({ italic: true }),
  'markdown.h7': new Style({ italic: true, dim: true }),
  'markdown.link': new Style({ color: 'bright_blue' }),
  'markdown.link_url': new Style({ color: 'blue', underline: true }),
  'markdown.s': new Style({ strike: true }),
  'iso8601.date': new Style({ color: 'blue' }),
  'iso8601.time': new Style({ color: 'magenta' }),
  'iso8601.timezone': new Style({ color: 'yellow' }),
};
